# Generated by Django 5.2.7 on 2025-11-25 00:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0004_alter_appointment_options_appointment_observations'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleFormsSync',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('synced_at', models.DateTimeField(auto_now_add=True)),
                ('total_new_responses', models.IntegerField(default=0)),
                ('successfully_registered', models.IntegerField(default=0)),
                ('duplicates_found', models.IntegerField(default=0)),
                ('errors', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('running', 'Executando'), ('completed', 'Concluída'), ('failed', 'Falhou')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('duration_seconds', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Sincronização de Google Forms',
                'verbose_name_plural': 'Sincronizações de Google Forms',
                'ordering': ['-synced_at'],
            },
        ),
        migrations.CreateModel(
            name='ProcessedGoogleFormSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(db_index=True, max_length=14, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('full_name', models.CharField(max_length=255)),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('processing', 'Processando'), ('success', 'Sucesso'), ('duplicate', 'Duplicado'), ('error', 'Erro')], default='pending', max_length=20)),
                ('patient_id_in_platform', models.CharField(blank=True, help_text='ID do paciente na plataforma GoC', max_length=50, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('attempts', models.IntegerField(default=0)),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('raw_form_data', models.JSONField(blank=True, null=True)),
                ('local_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.user')),
            ],
            options={
                'verbose_name': 'Submissão de Google Form Processada',
                'verbose_name_plural': 'Submissões de Google Forms Processadas',
                'ordering': ['-processed_at'],
            },
        ),
        migrations.CreateModel(
            name='PatientRegistrationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt_number', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('success', models.BooleanField(default=False)),
                ('message', models.TextField()),
                ('error_details', models.TextField(blank=True, null=True)),
                ('step', models.CharField(choices=[('validation', 'Validação'), ('cpf_check', 'Verificação de CPF'), ('login', 'Login'), ('navigation', 'Navegação'), ('form_fill', 'Preenchimento de Formulário'), ('form_submit', 'Envio de Formulário'), ('confirmation', 'Confirmação')], max_length=50)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='web_scraping.processedgoogleformsubmission')),
            ],
            options={
                'verbose_name': 'Log de Registro de Paciente',
                'verbose_name_plural': 'Logs de Registros de Pacientes',
                'ordering': ['-timestamp'],
            },
        ),
    ]
