# Generated by Django 5.2.7 on 2025-11-07 04:23

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'verbose_name': 'Agendamento', 'verbose_name_plural': 'Agendamentos'},
        ),
        migrations.AlterModelOptions(
            name='chatmessage',
            options={'verbose_name': 'Mensagem de Chat', 'verbose_name_plural': 'Mensagens de Chat'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Usuário', 'verbose_name_plural': 'Usuários'},
        ),
        migrations.AlterModelOptions(
            name='vaccine',
            options={'verbose_name': 'Vacina', 'verbose_name_plural': 'Vacinas'},
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='appointment_time',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='dose',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='via_chatbot',
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='from_user',
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='needs_human',
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='timestamp',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_vaccine',
        ),
        migrations.RemoveField(
            model_name='user',
            name='synced',
        ),
        migrations.RemoveField(
            model_name='user',
            name='via_chatbot',
        ),
        migrations.RemoveField(
            model_name='vaccine',
            name='current_stock',
        ),
        migrations.RemoveField(
            model_name='vaccine',
            name='expiry_date',
        ),
        migrations.RemoveField(
            model_name='vaccine',
            name='lot_number',
        ),
        migrations.RemoveField(
            model_name='vaccine',
            name='minimum_stock',
        ),
        migrations.AddField(
            model_name='appointment',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Observações'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 11, 7, 4, 23, 10, 419532, tzinfo=datetime.timezone.utc), verbose_name='Criado em'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='is_bot',
            field=models.BooleanField(default=False, verbose_name='É do Bot?'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='priority',
            field=models.CharField(choices=[('low', 'Baixa'), ('medium', 'Média'), ('high', 'Alta')], default='low', max_length=10, verbose_name='Prioridade'),
        ),
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='E-mail'),
        ),
        migrations.AddField(
            model_name='user',
            name='source',
            field=models.CharField(choices=[('chatbot', 'Chatbot'), ('manual', 'Manual')], default='chatbot', max_length=10, verbose_name='Origem'),
        ),
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendente'), ('synced', 'Sincronizado'), ('error', 'Erro')], default='pending', max_length=10, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Atualizado em'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='appointment_date',
            field=models.DateTimeField(verbose_name='Data do Agendamento'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Criado em'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Agendado'), ('confirmed', 'Confirmado'), ('completed', 'Realizado'), ('cancelled', 'Cancelado')], default='scheduled', max_length=10, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.user', verbose_name='Usuário'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='vaccine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.vaccine', verbose_name='Vacina'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='message',
            field=models.TextField(verbose_name='Mensagem'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='resolved',
            field=models.BooleanField(default=False, verbose_name='Resolvido?'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.user', verbose_name='Usuário'),
        ),
        migrations.AlterField(
            model_name='user',
            name='birth_date',
            field=models.DateField(verbose_name='Data de Nascimento'),
        ),
        migrations.AlterField(
            model_name='user',
            name='cpf',
            field=models.CharField(max_length=14, unique=True, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Criado em'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='vaccine',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nome da Vacina'),
        ),
    ]
