# Generated by Django 5.2.7 on 2025-11-07 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_appointment_options_alter_chatmessage_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'ordering': ['appointment_date', 'appointment_time']},
        ),
        migrations.AddField(
            model_name='appointment',
            name='observations',
            field=models.TextField(blank=True),
        ),
    ]
