# Generated by Django 5.2.7 on 2025-11-25 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_appointment_options_appointment_observations'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaccine',
            name='available_stock',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vaccine',
            name='laboratory',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vaccine',
            name='min_stock',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='vaccine',
            name='purchase_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='vaccine',
            name='sale_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
