# Generated by Django 5.2.7 on 2025-11-25 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_vaccine_available_stock_vaccine_laboratory_and_more'),
    ]

    operations = [
    ]
